import { google } from 'googleapis';

function getAuth() {
  return new google.auth.JWT(
    process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    null,
    process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, '\n'),
    ['https://www.googleapis.com/auth/spreadsheets']
  );
}

/**
 * Append a new transaction row to the Active Transactions sheet.
 * Maps form fields to the exact column order in Magenta_TC_Transaction_Management.xlsx.
 *
 * Column order (matches the Active Transactions tab):
 * A: File #       B: Status         C: Type          D: Agent
 * E: Brokerage    F: Property Addr  G: Client Name   H: Side
 * I: Sale Price   J: Loan Type      K: COE Date      L: Acceptance Date
 * M: EMD          N: Doc Platform   O: Escrow Co     P: Escrow Officer
 * Q: Escrow Email R: Lender         S: Lender Email  T: Notes
 * U: Drive Folder
 */
export async function appendNewFileRow(data) {
  const auth = getAuth();
  const sheets = google.sheets({ version: 'v4', auth });

  const row = [
    '',                              // A: File # — auto-generated by sheet formula
    'Open',                          // B: Status
    data.transactionType || '',      // C: Type
    data.agentName || '',            // D: Agent
    data.agentBrokerage || '',       // E: Brokerage
    data.propertyAddress || '',      // F: Property Address
    data.clientNames || '',          // G: Client Name(s)
    data.side || '',                 // H: Side (Buyer/Listing)
    data.salePrice || '',            // I: Sale Price
    data.loanType || '',             // J: Loan Type
    data.coeDate || '',              // K: COE Date
    data.acceptanceDate || '',       // L: Acceptance Date
    data.emd || '',                  // M: EMD
    data.docPlatform || '',          // N: Doc Platform
    data.escrowCompany || '',        // O: Escrow Company
    data.escrowOfficer || '',        // P: Escrow Officer
    data.escrowEmail || '',          // Q: Escrow Email
    data.lenderName || '',           // R: Lender
    data.lenderEmail || '',          // S: Lender Email
    data.notes || '',                // T: Notes
    data.driveFolderUrl || '',       // U: Drive Folder Link
  ];

  await sheets.spreadsheets.values.append({
    spreadsheetId: process.env.GOOGLE_SHEET_ID,
    range: 'Active Transactions!A:U',
    valueInputOption: 'USER_ENTERED',
    insertDataOption: 'INSERT_ROWS',
    requestBody: { values: [row] },
  });
}

/**
 * Append a new agent row to the Brokerage Directory sheet.
 */
export async function appendAgentRow(data) {
  const auth = getAuth();
  const sheets = google.sheets({ version: 'v4', auth });

  const row = [
    data.agentName || '',
    data.brokerage || '',
    data.email || '',
    data.phone || '',
    data.docPlatform || '',
    data.licenseNumber || '',
    new Date().toLocaleDateString('en-US'),
    data.notes || '',
  ];

  await sheets.spreadsheets.values.append({
    spreadsheetId: process.env.GOOGLE_SHEET_ID,
    range: 'Brokerage Directory!A:H',
    valueInputOption: 'USER_ENTERED',
    insertDataOption: 'INSERT_ROWS',
    requestBody: { values: [row] },
  });
}
